<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="3" failures="1" disabled="0" errors="0" timestamp="2020-06-12T20:27:51" time="0.006" random_seed="388" name="AllTests">
  <testsuite name="ConfigStoreTests" tests="3" failures="1" disabled="0" errors="0" time="0.005">
    <testcase name="WriterCanAddEntryToFile" status="run" time="0.003" classname="ConfigStoreTests" />
    <testcase name="DeleteTempFile" status="run" time="0" classname="ConfigStoreTests">
      <failure message="../../../tests/config_store_tests.cc:107&#x0A;Value of: res == false || errno == EEXIST&#x0A;  Actual: false&#x0A;Expected: true&#x0A;2" type=""><![CDATA[../../../tests/config_store_tests.cc:107
Value of: res == false || errno == EEXIST
  Actual: false
Expected: true
2]]></failure>
    </testcase>
    <testcase name="WriterCanCreateFile" status="run" time="0.002" classname="ConfigStoreTests" />
  </testsuite>
</testsuites>
